### ISSUE TITLE
literally unplayable

### ISSUE THREAD

**Issue by mikelat** [RedRafe/py-tweaks#1]
![image](https://github.com/RedRafe/py-tweaks/assets/14167635/f867e378-dcc9-4de3-8ba3-955faf2ffea2)

**Comment by RedRafe** [comment]
<img width="917" alt="Schermata 2023-05-27 alle 19 29 18" src="https://github.com/RedRafe/py-tweaks/assets/93430988/5bbbba78-b248-4a05-a7aa-f94fcae5baf3">
